library(dplyr)
library(Strategus)

# Time-at-risks (TARs) for the outcomes of interest in your study
timeAtRisks <- tibble(
  label = c("Year 1", "Year 2", "Year 3", "Year 4"),
  riskWindowStart  = c(0, 365, 730, 1095),   # CONFIRM start at 0
  startAnchor = c("cohort start"),
  riskWindowEnd  = c(365, 730, 1095, 1460),
  endAnchor = c("cohort end")
)

studyStartDate <- '20210101' #YYYYMMDD
studyEndDate <- '20241231'   #YYYYMMDD

# Some of the settings require study dates with hyphens
studyStartDateWithHyphens <- gsub("(\\d{4})(\\d{2})(\\d{2})", "\\1-\\2-\\3", studyStartDate)
studyEndDateWithHyphens <- gsub("(\\d{4})(\\d{2})(\\d{2})", "\\1-\\2-\\3", studyEndDate)


# Shared Resources -------------------------------------------------------------
# NOTE: Generated by DownloadCohorts.R
cohortDefinitionSetLimited <- CohortGenerator::getCohortDefinitionSet(
  settingsFileName = "inst/cohorts_limited.csv",
  jsonFolder = "inst/cohorts/limited",
  sqlFolder = "inst/sql/sql_server/limited"
)



if (any(duplicated(cohortDefinitionSetLimited$cohortId))) {
  stop("*** Error: duplicate cohort IDs found ***")
}

# Create some data frames to hold the cohorts we'll use in each analysis ---------------
# Outcomes: The outcomes for this study take values >= 100
oList <- cohortDefinitionSetLimited |>
  filter(cohortId >= 100) |>
  mutate(outcomeCohortId = cohortId, outcomeCohortName = cohortName) |>
  select(outcomeCohortId, outcomeCohortName) |> 
  mutate(cleanWindow = 0)

# CohortGeneratorModule --------------------------------------------------------
cgModuleSettingsCreator <- CohortGeneratorModule$new()
cohortDefinitionShared <- cgModuleSettingsCreator$createCohortSharedResourceSpecifications(cohortDefinitionSetLimited)

cohortGeneratorModuleSpecifications <- cgModuleSettingsCreator$createModuleSpecifications(
  generateStats = TRUE
)

# TreamentPatternsModule Settings ---------------------------------
tpSettingsCreator <- Strategus::TreatmentPatternsModule$new()

# We need four specifications for the treatment patterns module, one for each indication cohort.
tpTargetCohorts <- cohortDefinitionSetLimited |>
  mutate(
    type = case_when(
      cohortId < 100 ~ "target",
      cohortId >= 100 ~ "event"
    )
  ) |>
  select(
    cohortId,
    cohortName,
    type
  ) 

treatmentPatternsModuleSpecifications <- tpSettingsCreator$createModuleSpecifications(
  cohorts = tpTargetCohorts,
  includeTreatments = "startDate",
  indexDateOffset = 0,
  minEraDuration = 0,
  splitEventCohorts = NULL,
  splitTime = NULL,
  eraCollapseSize = 0,
  combinationWindow = 0,
  minPostCombinationDuration = 0,
  filterTreatments = "Changes",
  maxPathLength = 5
)

# Create the analysis specifications ------------------------------------------
analysisSpecifications <- Strategus::createEmptyAnalysisSpecificiations() |>
  Strategus::addSharedResources(cohortDefinitionShared) |> 
  Strategus::addModuleSpecifications(cohortGeneratorModuleSpecifications) |>
  Strategus::addModuleSpecifications(treatmentPatternsModuleSpecifications)

ParallelLogger::saveSettingsToJson(
  analysisSpecifications, 
  file.path("inst", "drScreeningStudyAnalysisSpecificationTreatmentPatterns.json")
)